name: docs/gh-pages
on:
  create:
    tags:
      - *
  schedule:
    - cron: '0 3 * * *' # run every night at 3AM

jobs:
    build-docs:
        name: Build docs and push to gh-pages
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout branch
              uses: actions/checkout@v2

            - name: Setup python 
              uses: actions/setup-python@v2
              with:
                python-version: 3.8
            
            - name: Install poetry
              uses: dschep/install-poetry-action@v1.3
            
            - name: Install dependencies
              run: poetry install
            
            - name: build docs
              run: |
                cd docs
                make clean
                make html
                cd ..
            
            - name: deploy to gh-pages
              uses: Cecilapp/GitHub-Pages-deploy@master
              env:
                EMAIL: dhagan@mit.edu
                GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                BUILD_DIR: docs/_build/html